chore: update dependencies
Informasjonsforvaltning/fdk-reasoning-service pull request #202
Opened 2024-08-29 07:31 UTC by NilsOveTen

2024-08-29 07:39 UTC, jeffreiffers approved these changes

2024-08-29 08:14 UTC, jeffreiffers requested changes

2024-08-29 08:14 UTC, jeffreiffers commented on src/main/kotlin/no/fdk/fdk_reasoning_service/kafka/KafkaHarvestedEventCircuitBreaker.kt
> +                LOGGER.debug("Event was ignored: {}", event.toString())
```suggestion
                LOGGER.warning("Event was ignored: {}", event.toString())
```

2024-08-29 08:16 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_reasoning_service/kafka/KafkaHarvestedEventCircuitBreaker.kt
> +                LOGGER.debug("Event was ignored: {}", event.toString())
får vi ikke da warning-spam på alle *_REMOVED og *_REASONED?

2024-08-29 08:27 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_reasoning_service/kafka/KafkaHarvestedEventCircuitBreaker.kt
> +                LOGGER.debug("Event was ignored: {}", event.toString())
jepp, ble veldig vanskelig å lese debug loggen med denne. Fjerna.

2024-08-30 04:59 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/fdk_reasoning_service/kafka/KafkaHarvestedEventCircuitBreaker.kt
> +                LOGGER.debug("Event was ignored: {}", event.toString())
88ba1c0717aa0eb80275c85c1c9c33adbe359d94

La den tilbake som warning, men sammen med spesifikk håndtering av de forventede typene.

2024-08-30 12:19 UTC, jeffreiffers approved these changes

2024-08-30 12:29 UTC, merged